### ISSUE TITLE
Callback macro for expired maintenance

### ISSUE THREAD

**Issue by AlejandroRivera** [3DCoded/KlipperMaintenance#1]
Could we have a way to register a macro that gets called when a  maintenance is expired when using `MAINTAIN_STATUS`?

For example, I'd like to invoke `MAINTAIN_STATUS` when the printer finishes booting up and after a print is finished; however is unlikely that I'll be looking at logs unless i get an M117 display msg and/or a "beep" pattern from the machine.

**Comment by 3DCoded** [comment]
Thank you for your feature request. I am working on this implementation in the `dev` branch and will update here when it is completed.

**Comment by 3DCoded** [comment]
Experimental support is now available in the `main` branch. To get the updated functionality, follow [Updating](https://3dcoded.github.io/KlipperMaintenance/install/#update), then read the updated [Configuration Documentation](https://3dcoded.github.io/KlipperMaintenance/config/#maintenance-sections).

**Comment by AlejandroRivera** [comment]
Thanks a bunch! I'll give it a try asap.

**Comment by AlejandroRivera** [comment]
Hmmm... it seems I had misunderstood how things work.

I thought the only time an expiration event would get triggered was if I executed the `MAINTAIN_STATUS` command. 

Instead, it seems this project continuously evaluates all maintenance objects every X amount of time (as defined by `[maintain]`'s `interval` property) and if a maintenance object is expired, the event is triggered every time until the `UPDATE_MAINTENANCE` command is called.

This presents a problem for me because in a scenario where i define a config like so:
```
[maintain]
interval: 60         # in  seconds (i.e. 1 min)

[maintain test]
label: test
trigger: time
threshold: 1        #in hours
message: Maintenance Test
expired_gcode:
  BEEP TIMES=5 
  M117 "MAINT: test"
```

and I'm in the middle of printing a 5-hour long job, right after 1 hour, my printing GCODE will be paused to execute 5 beeps, and my LCD will display the `MAINT: test` message. This is already a problem because during the pause for beeping, my nozzle will be oozing filament, and on top of that (without me being able to actually perform any maintenance on the machine because it's still printing), I'll get the same reminder with 5 beeps after 1 minute because the next evaluation interval is finished, and so on, every minute until i execute `UPDATE_MAINTENANCE NAME=test` to reset the timer for another hour.

I understand that i could use gcode to detect if the machine is printing and skip the rest of the actions, but even if the machine isn't printing, i would have expected a single expiration event to take place once, and not every minute (because what happens if I'm away or sleeping?). Of course, i could also do something to store the fact that this gcode is only executed once, but it feels a bit "hacky" and perhaps there's a better solution.

Do you have any suggestions of how to handle a scenario like the one above? Are there less hacky approaches you can suggest?

For example, could i disable the continuos evaluation by using `interval: 0` and depend only on `MAINTAIN_STATUS` to check if the threshold has elapsed?

**Comment by 3DCoded** [comment]
> For example, could i disable the continuos evaluation by using interval: 0 and depend only on MAINTAIN_STATUS to check if the threshold has elapsed?

I've implemented this into the `feat-not_automatic` branch. To install it:

```
cd ~/KlipperMaintenance
git fetch
git checkout feat-not_automatic
git pull
sh install.sh
sudo service klipper restart
```

Let me know if this works.

**Comment by 3DCoded** [comment]
This feature is now available in the `main` branch. To switch back to the main branch:

```
cd ~/KlipperMaintenance
git fetch
git checkout main
git pull
sh install.sh
sudo service klipper restart
```
