### ISSUE TITLE
Feature Request: Add total machine working hours counter

### ISSUE THREAD

**Issue by darbogx** [3DCoded/KlipperMaintenance#2]
Hi, you have done a great job with this addition. Would it be possible to add an option to also download a counter of hours worked by the machine (without service intervals)? I know the purpose of this add-on is different, but this function would also be useful.

**Comment by 3DCoded** [comment]
> download a counter of hours worked by the machine (without service intervals)

Are you talking about the total print time, like in the History panel of Mainsail/Fluidd?

<img width="769" alt="Untitled" src="https://github.com/user-attachments/assets/27eb4886-99fb-4de6-8270-da757df0329c">

Do you want this information available in a macro like this?

```
[gcode_macro DISPLAY_HOURS]
gcode:
    RESPOND MSG="{maintain.total.print_time} Hours"
```

Let me know.

**Comment by darbogx** [comment]
Oh God... 
I don't even know why I did not find this earlier....
That is what i need.
