### ISSUE TITLE
Feature Request: Modify working hours 

### ISSUE THREAD

**Issue by llambion72** [3DCoded/KlipperMaintenance#3]
Thank you for your great work with this addon. I was using some macros but this is much better.
Would it be possible to add a command to modify the printing hours that we have before doing maintenance on the configured parts?
I kept the count in an Excel sheet and I would like to add those printing hours to this addon and not have it start from zero, but with another value.

Such as,

UPDATE_MAINTENANCE_WORKING_HOURS NAME=xyrods HOURS=95

**Comment by 3DCoded** [comment]
Just to clarify, when the following command is run:
```
UPDATE_MAINTENANCE_WORKING_HOURS NAME=xyrods HOURS=95
```

the `threshold` parameter in your configuration for `xyrods` should be automatically changed to `95`?

**Comment by llambion72** [comment]
No, when i run 
UPDATE_MAINTENANCE_WORKING_HOURS NAME=xyrods HOURS=95

set xyrods worked hours to 95, like 

UPDATE_MAINTENANCE NAME=xyrods 

but instead set worked hours to 0, set to 95

**Comment by 3DCoded** [comment]
Ok. So if the threshold is set to 100 hours and you run:

```
UPDATE_MAINTENANCE NAME=xyrods HOURS=20
```

There will be 80 hours remaining until the maintenance is triggered.

**Comment by 3DCoded** [comment]
This is implemented in the latest commit.
